// check vowel and consonent using ladder if else

/*public class vowelconsonant
{
    public void vowe()
    {
        string ch= 'e';
        if(ch=='a')
        {
            system.debug(ch + ' is vowel');
        }
        else if (ch=='e')
        {
            system.debug(ch+' is vowel');
        }
        else if (ch=='i')
        {
            system.debug(ch+' is vowel');
        }
        else if (ch=='o')
        {
            system.debug(ch+' is vowel');
        }
        else if (ch=='u')
        {
            system.debug(ch+' is vowel');
        }
        else
        {
            system.debug(ch+' is consonent');
        }
        
        
    }
}*/

// WAP to check vowel consonent using blank string=

/*public class vowelcons
{
   public void vowe()
   {
       string word = 'z';
       string s='';
       if(word=='a')
       {
        s='vowel';   
       }
       else if (word=='e')
       {
           s='vowel';
       }
       else if (word=='i')
       {
           s='vowel';
       }
       else if (word=='o')
       {
           s='vowel';
       }
       else if (word=='u')
       {
           s='vowel';
       }
       else
       {
           s='consonent';
       }
       system.debug(s);
   }
}*/

// wap to display yes for y , no for n , cancel for c,and other for rest;

public class display
{
    public void dis()
    {
        string word='c';
        if(word=='y')
        {
            system.debug('yes');
        }
        else if (word=='n')
        {
            system.debug('no');
        }
        else if (word=='c')
        {
            system.debug('cancel');
        }
        else
        {
            system.debug('others');
        }
    }
}